/** CAN message encoder/decoder: automatically generated - do not edit
  * Generated by dbcc: See https://github.com/howerj/dbcc */
#ifndef CAN_E_H
#define CAN_E_H

/* If the contents of this file have caused breaking changes for you, you could try using
   an older version of the generator. You can specify this on the command line with
   the -n option. */
#define DBCC_GENERATOR_VERSION (3)

#include <stdint.h>
#include <stdio.h>

#ifdef __cplusplus
extern "C" { 
#endif

#ifndef PREPACK
#define PREPACK
#endif

#ifndef POSTPACK
#define POSTPACK
#endif

#ifndef DBCC_TIME_STAMP
#define DBCC_TIME_STAMP
typedef uint32_t dbcc_time_stamp_t; /* Time stamp for message; you decide on units */
#endif

#ifndef DBCC_STATUS_ENUM
#define DBCC_STATUS_ENUM
typedef enum {
	DBCC_SIG_STAT_UNINITIALIZED_E = 0, /* Message never sent/received */
	DBCC_SIG_STAT_OK_E            = 1, /* Message ok */
	DBCC_SIG_STAT_ERROR_E         = 2, /* Encode/Decode/Timestamp/Any error */
} dbcc_signal_status_e;
#endif

#define CAN_ID_DCU_1 (369) /* 0x171 */
#define CAN_ID_BMS_18 (685) /* 0x2ad */

typedef PREPACK struct {
	uint16_t DCU_RotSpdAct; /* scaling 1.0, offset -32766.0, units rpm  */
	uint16_t DCU_IdcAct; /* scaling 1.0, offset -1023.0, units A  */
	uint16_t DCU_TorqAct; /* scaling 1.0, offset -1023.0, units Nm  */
	uint16_t DCU_UdcAct; /* scaling 1.0, offset 0.0, units V  */
} POSTPACK can_0x171_DCU_1_t;

typedef PREPACK struct {
	uint16_t BMS_BattSocDisp; /* scaling 0.1, offset 0.0, units %  */
} POSTPACK can_0x2ad_BMS_18_t;

typedef PREPACK struct {
	dbcc_time_stamp_t can_0x171_DCU_1_time_stamp_rx;
	dbcc_time_stamp_t can_0x2ad_BMS_18_time_stamp_rx;
	unsigned can_0x171_DCU_1_status : 2;
	unsigned can_0x171_DCU_1_tx : 1;
	unsigned can_0x171_DCU_1_rx : 1;
	unsigned can_0x2ad_BMS_18_status : 2;
	unsigned can_0x2ad_BMS_18_tx : 1;
	unsigned can_0x2ad_BMS_18_rx : 1;
	can_0x171_DCU_1_t can_0x171_DCU_1;
	can_0x2ad_BMS_18_t can_0x2ad_BMS_18;
} POSTPACK can_obj_can_e_h_t;

int unpack_message(can_obj_can_e_h_t *o, const unsigned long id, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp);
int pack_message(can_obj_can_e_h_t *o, const unsigned long id, uint64_t *data);
int print_message(const can_obj_can_e_h_t *o, const unsigned long id, FILE *output);

int decode_can_0x171_DCU_RotSpdAct(const can_obj_can_e_h_t *o, double *out);
int encode_can_0x171_DCU_RotSpdAct(can_obj_can_e_h_t *o, double in);
int decode_can_0x171_DCU_IdcAct(const can_obj_can_e_h_t *o, double *out);
int encode_can_0x171_DCU_IdcAct(can_obj_can_e_h_t *o, double in);
int decode_can_0x171_DCU_TorqAct(const can_obj_can_e_h_t *o, double *out);
int encode_can_0x171_DCU_TorqAct(can_obj_can_e_h_t *o, double in);
int decode_can_0x171_DCU_UdcAct(const can_obj_can_e_h_t *o, uint16_t *out);
int encode_can_0x171_DCU_UdcAct(can_obj_can_e_h_t *o, uint16_t in);


int decode_can_0x2ad_BMS_BattSocDisp(const can_obj_can_e_h_t *o, double *out);
int encode_can_0x2ad_BMS_BattSocDisp(can_obj_can_e_h_t *o, double in);


#ifdef __cplusplus
} 
#endif

#endif
